### PR TITLE
WIP Fix decoding of bytes from redis data.

### PR DESCRIPTION
**Pull request by rolando**

### CODE REVIEW

**Comment by makelove** [comment]
------
def make_request_from_data(self, data):
        # By default, data is an URL.
        if not isinstance(data, six.string_types):
            # XXX: Shall we log and continue?
            raise TypeError("Wrong type for data: %s" % type(data))
------
Why don't  log it and continue  ???

**Comment by makelove** [comment]
As in fact
you should use this:
redis.StrictRedis(host="localhost", port=6379, charset="utf-8", decode_responses=True)

it work on py2 and py3

Suggestion

**Comment by makelove** [comment]
put this code in scrapy setting.py, redis lpop return a unicode,not betyes,it work,but other error show up:
####
# Custom redis client parameters (i.e.: socket timeout, etc.)
REDIS_PARAMS  = {}
# Use custom redis client class.
#REDIS_PARAMS['redis_cls'] = 'myproject.RedisClient'
REDIS_PARAMS['charset'] = 'utf-8'
REDIS_PARAMS['decode_responses'] = True
####
ERROR:
  File "/home/xxx/py3/lib/python3.5/site-packages/redis/connection.py", line 280, in read_response
    response = response.decode(self.encoding)
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
----
the response is
b'\x80\x04\x95\xa9\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\x03url\x94\x8c\x1ahttps://www.xxxx.com/\x94\x8c\x06method\x94\x8c\x03GET\x94\x8c\x08callback\x94N\x8c\x07errback\x94N\x8c\x07headers\x94}\x94\x8c\x04meta\x94}\x94\x8c\t_encoding\x94\x8c\x05utf-8\x94\x8c\x04body\x94C\x00\x94\x8c\x07cookies\x94}\x94\x8c\x08priority\x94K\x00\x8c\x0bdont_filter\x94\x88u.'

**Comment by rolando** [comment]
@makelove Start URLs, by default, are expected to be strings. At the other hand, serialized requests can be bytes.

The type error is there to stop processing a bad queue. It can happen when the user uses the wrong queue (i.e.: serialized requests).

**Pull request merged**
